steps:
# auth_login 関数のデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'functions'
  - 'deploy'
  - 'auth-login'
  - '--gen2'
  - '--region=us-central1' # ★ リージョンを直接指定 (成功した実績のあるリージョン)
  - '--runtime=python310'
  - '--source=./auth_functions'
  - '--entry-point=auth_login_route'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,STREAMLIT_APP_URL=STREAMLIT_APP_URL:latest'
  - '--set-env-vars=GCP_PROJECT=${PROJECT_ID},FUNCTION_REGION=us-central1,ENV=production,FUNCTION_BASE_URL=https://us-central1-${PROJECT_ID}.cloudfunctions.net'

# auth_callback 関数のデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'functions'
  - 'deploy'
  - 'auth-callback'
  - '--gen2'
  - '--region=us-central1' # ★ リージョンを直接指定
  - '--runtime=python310'
  - '--source=./auth_functions'
  - '--entry-point=auth_callback_route'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,STREAMLIT_APP_URL=STREAMLIT_APP_URL:latest'
  - '--set-env-vars=GCP_PROJECT=${PROJECT_ID},FUNCTION_REGION=us-central1,ENV=production,FUNCTION_BASE_URL=https://us-central1-${PROJECT_ID}.cloudfunctions.net'

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
