# streamlit_app/.streamlit/secrets.toml

# Cloud Functionsの/loginエンドポイントのURL (ローカルテスト時)
# 本番デプロイ時は、デプロイされたCloud Functionの実際のURLに書き換える
AUTH_SERVER_LOGIN_URL = "http://localhost:8080/auth_login"

# JWTを検証するためのキー (Cloud Functions側のJWT_SECRET_KEYと全く同じ値)
JWT_VERIFY_KEY = "e1c5ef28797cba9a3d55ecd943520237fe4c8f68dbdf3b5a4b385167f04681bd" # ★ Cloud Functionsの.envのJWT_SECRET_KEYと同じ値

# Streamlitアプリ自身のURL (JWTのaudience検証用)
# ローカルテスト時は通常この値
STREAMLIT_APP_URL = "http://localhost:8501"